services:
  english_dojo:
    container_name: english_dojo_api
    build:
      context: .
      dockerfile: Dockerfile
    image: english_dojo_api
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    extra_hosts:
      - host.docker.internal:host-gateway

  postgres:
    image: postgres:16
    container_name: english_dojo_postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: english_dojo_redis
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
